<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.CloudFormation" Version="4.0.102.6" />
        <PackageReference Include="AWSSDK.ECS" Version="4.0.105" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.103.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Cicd.Utils/Cicd.Utils.csproj" />
    </ItemGroup>
</Project>